<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>internal_search_backend</RootNamespace>
    <UserSecretsId>232f0667-6f89-406a-8715-18760e5610f2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\internal-search-backend.Business\internal-search-backend.Business.csproj" />
    <ProjectReference Include="..\internal-search-backend.Infraestructure\internal-search-backend.Infraestructure.csproj" />
    <ProjectReference Include="..\internal-search.Domain\internal-search-backend.Domain.csproj" />
  </ItemGroup>

</Project>
